---
title: EES2019 Stacking Process 
subtitle: Generic Distance/Proximity Variables Estimation 
author: Giuseppe Carteny
date: 09.09.2021 
toc: true
output: 
  bookdown::pdf_document2:
    includes:
      in_header: First_steps_header.tex
urlcolor: RedOrange
--- 

# Introduction 

Our next tasks consist in (1) the estimation of generic **distance/proximity** variables and (2) the 
preparation of the SDM codebook.

The workflow follows up the one used for our previous task: we will modify the 'genvars' country-specific 
scripts developed a few days ago, adding the computation of the distance/proximity variables. 

# Estimating Generic Distance/Proximity Variables and Codebook Preparation

As suggested by their name, distance/proximity variables concern the distance or proximity between the 
voter and the set of relevant parties on some dimensions of interest. Thus, such variables measure 
whether and to what extent the position of an individual is more or less close to/distant from the 
position of a party on general dimensions (for istance, the left-right continuum) or on specific issues 
(such as European integration, immigration policies, minority rights, and so on). As shown below, we 
will estimate distance rather than proximity variables. Thus, the higher the values of such variables 
the more distant a specific voter and a specific party are. 

## Distance as Absolute Difference

Theoretically, for estimating distances between voters and parties we could use a geometric distance 
formula: 

> $d = \sqrt{(x_i - x_k)^2 + (y_i - y_k)^2}$

Where $x_i$ and $y_i$ represent the positions of individual $i$ on issues $x$ and $y$, and $x_k$ and 
$y_k$ represent the position of party $k$ on the same issues. Since we are computing individual-party 
distances on a single issue, this implies that we are estimating these distances on a single axis. 
Thus, we can drop the second half of the formula below the radical symbol, rewriting the formula as it 
follows:

> $d = \sqrt{(x_i - x_k)^2}$

Nonetheless, these values are usually computed using a similar formula, avoiding the radical and simply 
using the absolute difference of individual and party positions, that is: 

> $d = |x_i - x_k|$

This is the formula that we will use in our scripts. 

## The `gendis.fun` function 

As in the case of dichotomous variables, for computing generic distance variables I implemented a 
function that will make our job much easier. This `gendis.fun` is slightly more elaborated than the one 
used before. In short, it will take the value of an individual on a given dimension (say, respondents' 
self-placement on the left-right ideological axis, variable `Q11`) and the value of a party on the same 
dimension *as perceived by the same individual* (hence, an idiosyncratic value as specified in the `Q13` 
variables set) or *as perceived by all the respondents* (thus, an average value of respondents' scores on 
the same set of variables). These two methods are not the only one for computing such distance variables,
but for now we will rely on these ones, and more specifically on the second method. 

Returning to the function, as you will see it takes several arguments, thus a little presentation is 
needed. The `gendis.fun` arguments are the following:

.  `data` = The main data basis for computing our variables. Essentially it takes only one value, 
that is the 'EES2019' original data frame, thus this argument could be avoided. However, the function 
might be generalized in the following weeks to allow different data sources, that's why this argument is
there. 

.  `cdbk` = The auxiliary data frame for computing our variables. As above, it takes only one value, 
that is the 'EES2019_cdbk' data frame. However, also this argument has been implement because of 
possible implementations. The reason why we use the EES codebook is that it allows to automatically 
select the EES2019 columns referring to party positions. This leaves our hands free from manual coding 
(that is always a good thing).

.  `vrbl` = This argument so far takes three values: `Q10`, `Q11`, and `Q23`. The first one is our 



## Which Variables

The list of variables that we are going to use for computing our generic distance variables are the 
following: 

* **`Q10`**: Respondent's propensity to vote for a specific party;
* **`Q11`**: Respondent's self-placement on the left-right *continuum*;
* **`Q13`**: Respondent's perception of a specific party position on the left-right *continuum*;
* **`Q23`**: Respondent's position about EU integration^[In the original 
[EES 2019 Master Questionnaire](https://dbk.gesis.org/dbksearch/download.asp?id=67447) reference is made 
to EU *unification* rather than *integration* process. Nonetheless, the two concepts can be considered 
almost equivalent.];
* **`Q24`**: Respondent's perception of a specific party position on the EU integration process.

